services:
  uglyfeed: # Defines a service named 'uglyfeed'.
    restart: always
    build: .
    ports:
      - "18001:8001" # Maps port 8001 on the host to port 8001 in the container.
      - "18501:8501" # Maps port 8501 on the host to port 8501 in the container.
    volumes:
      - ./input/feeds.txt:/app/input/feeds.txt # Mounts the local file 'feeds.txt' to '/app/input/feeds.txt' in the container.
      - ./config.yaml:/app/config.yaml # Mounts the local file 'config.yaml' to '/app/config.yaml' in the container.
    networks:
      - uglyfeed_network # Connects the service to the specified network 'uglyfeed_network'.

# Defines networks to be used by the services.
networks:
  uglyfeed_network: # This network will be used by the 'uglyfeed' service.
    name: uglyfeed # Specifies that the network named 'uglyfeed' is external, meaning it should already exist and not be managed by this Compose file.
